volumes:
  mariadb:
    driver: local
  mongo-data:
    driver: local
#   volumes-nfs-share:
#     driver: local
#     driver_opts:
#       type: "nfs4"
#       o: "addr=192.168.1.3,rw"
#       device: ":/dockervolumes"

networks:
  api-net:
    #driver: bridge

services: 
    api-service:
        build: 
            context: ./api
            dockerfile: Dockerfile
        ports: 
            - "8080:8080"
        networks:
            - api-net

#################################################################################

    mongodb-service:
        image: mongo:latest
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=wasd
            - MONGO_INITDB_DATABASE=apidemo
        volumes:
            - mongo-data:/data/db
        networks:
            - api-net

    mongo-express-service:
        image: mongo-express:latest
        restart: always
        ports:
            - "8081:8081"
        environment:
            - ME_CONFIG_BASICAUTH=false
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=wasd
            - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
            - ME_CONFIG_MONGODB_AUTH_PASSWORD=wasd
            - ME_CONFIG_MONGODB_URL=mongodb://admin:wasd@mongodb-service:27017/
        networks:
            - api-net

#################################################################################

    mariadb-service:
        image: mariadb:10.4
        container_name: mariadb-container
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
            MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: ${MARIADB_ALLOW_EMPTY_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
        expose:
            - "3306"
        ports:
            - "3306:3306"
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - api-net

    phpmyadmin-service:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-container
        restart: always
        expose:
            - "81"
        ports:
            - "81:80"
        environment:
            - PMA_HOST=mariadb-service
            - PMA_PORT=3306 
        networks:
            - api-net

#################################################################################